### ISSUE TITLE
run_exp crashes when used concurrently

### ISSUE THREAD

**Issue by LasseThostrup** [mjasny/expinfo#4]
If one opens two shells on same server and register `run_exp experiment`, when stopping experiment at the same time one of them can encounter a BlockingIOError.

Afterwards, an experiment is still registered but the actual experiment processes is dead.

Stack trace:
```
Traceback (most recent call last):
  File "/usr/local/bin/run_exp", line 78, in main
    p.wait()
  File "/usr/lib/python3.6/subprocess.py", line 1477, in wait
    (pid, sts) = self._try_wait(0)
  File "/usr/lib/python3.6/subprocess.py", line 1424, in _try_wait
    (pid, sts) = os.waitpid(self.pid, wait_flags)
  File "/usr/local/bin/run_exp", line 65, in <lambda>
    clean_shutdown = lambda sig, frame: exit(my_id)
  File "/opt/expinfo/utils/helper.py", line 101, in exit
    job = DBHelper.rm(my_id)
  File "/opt/expinfo/utils/helper.py", line 19, in rm
    with JobDB(DB_FILE, timeout=1) as f:
  File "/opt/expinfo/utils/job_db.py", line 25, in __enter__
    fcntl.flock(self._fp.fileno(), fcntl.LOCK_EX | fcntl.LOCK_NB)
BlockingIOError: [Errno 11] Resource temporarily unavailable
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/local/bin/run_exp", line 85, in <module>
    main()
  File "/usr/local/bin/run_exp", line 80, in main
    exit(my_id)
  File "/opt/expinfo/utils/helper.py", line 101, in exit
    job = DBHelper.rm(my_id)
  File "/opt/expinfo/utils/helper.py", line 19, in rm
    with JobDB(DB_FILE, timeout=1) as f:
  File "/opt/expinfo/utils/job_db.py", line 25, in __enter__
    fcntl.flock(self._fp.fileno(), fcntl.LOCK_EX | fcntl.LOCK_NB)
BlockingIOError: [Errno 11] Resource temporarily unavailable
````

**Comment by mjasny** [comment]
Couldn't reproduce this issue. There is already a timeout in the code which should handle concurrent access to obtain the file lock required to the json-database file.
